bitclick/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static

urlpatterns = [
	path('', include('main.urls')),
    path('admin/', admin.site.urls),
   
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path
from . import views

app_name = "main"

urlpatterns = [
	path("", views.homepage, name="homepage"),
	path("register/", views.register, name="register"),
	path("login", views.login_request, name="login"),
	path("logout", views.logout_request, name="logout"),
	path("create/", views.createpost, name="create"),
	path("send/", views.sendData, name="send"),
	path("zender/", views.zender, name="zender"),
	
	
	
]

main/models.py
from django.db import models
from django.contrib.auth.models import User
from datetime import datetime


# Create your models here.

class Chart(models.Model):


    countries=models.CharField(max_length=500)
    
    numbers=models.IntegerField()
    

    

    class Meta:
        verbose_name_plural = "Chart"

    def __str__(self):
        return self.countries



class DataProcess(models.Model):
    email = models.EmailField()
    file = models.FileField(upload_to='media/')
    body = models.TextField()
    author = models.ForeignKey(User, default=None,on_delete=models.SET_DEFAULT)
    

    class Meta:
        verbose_name_plural = "DataProcess"

    def __str__(self):
        return self.email







class Post(models.Model):
    title=models.FileField(upload_to='media/')
    content= models.TextField()



class MessageUs(models.Model):
    email1= models.EmailField()
    yMessage= models.TextField()
    date = models.DateTimeField("date sent", default=datetime.now())

main/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm                                                                                       
from django.contrib.auth.models import User
from . import models

class NewUserForm(UserCreationForm):
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = ("username", "email", "password1", "password2")

    def save(self, commit=True):
        user = super(NewUserForm, self).save(commit=False)
        user.email = self.cleaned_data["email"]
        if commit:
            user.save()
        return user



class DataSubmitForm(forms.Form):
    email = forms.EmailField()
    file = forms.FileField()
    body = forms.CharField(widget=forms.Textarea)
    


   

    

main/views.py
from django.conf import settings
from django.shortcuts import render,redirect
from django.http import HttpResponse
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import  login,logout, authenticate
from django.contrib import messages
from django.core.mail import send_mail
from .forms import NewUserForm,DataSubmitForm
from .models import Chart,DataProcess,Post,MessageUs
from django.contrib.auth.decorators import login_required
from . import forms



# Create your views here.
def homepage(request):
	return render(request=request,
				  template_name="main/header.html",
				  context={"market": Chart.objects.all})

	

def sendData(request):
		if request.method == 'POST':
			if request.POST.get('email') and request.POST.get('file') and request.POST.get('message') :
				data=DataProcess()
				data.email= request.POST.get('email')
				data.file= request.POST.get('file')
				data.body= request.POST.get('message')
				data.author = request.user
				data.save()
				messages.info(request, "Your Data has Been Sent")
				return render(request,'main/header.html')
 

		else:
			   return redirect('main:homepage')			
 


def createpost(request):
		if request.method == 'POST':
			if request.POST.get('title') and request.POST.get('content'):
				post=Post()
				post.title= request.POST.get('title')
				post.content= request.POST.get('content')
				post.save()
				
				return render(request,'main/header.html')
 

		else:
			   return redirect('main:homepage')

def zender(request):
		if request.method == 'POST':
			if request.POST.get('email1') and request.POST.get('yMessage') and request.POST.get('date'):
				post=MessageUs()
				post.email1= request.POST.get('email1')
				post.yMessage= request.POST.get('yMessage')
				post.date= request.POST.get('date')
				post.save()
				# sending email to user
				zEmail = request.POST.get('email1')
				subject='Data-Farm'
				Emessage='Thank you for sending us a message,  We will be with you shortly'
				from_email=settings.EMAIL_HOST_USER
				to_list=[zEmail]
				send_mail(
				     subject,
				     Emessage,
				     from_email,
				     to_list,
				    fail_silently=False,
				)
				messages.info(request, "Message has been Sent...Kindly wait for response")
				messages.info(request, f"An Email has been Sent to {zEmail}")
				return render(request,'main/header.html')
 

		else:
			   return redirect('main:homepage')

def register(request):
	if request.method == "POST":
		form =NewUserForm(request.POST)
		if form.is_valid():
			user = form.save()
			username = form.cleaned_data.get('username')
			# sending email to user
			sEmail = form.cleaned_data.get('email1')
			subject='Appreciation From Data-Farm'
			Emessage='Thank you for singning up onto Data-Farm, we are here to./n We promise to give you the best of our services '
			from_email=settings.EMAIL_HOST_USER
			to_list=[user.email]
			send_mail(
			     subject,
			     Emessage,
			     from_email,
			     to_list,
			    fail_silently=False,
			)
			messages.success(request, f"New Account Created: {username}")
			login(request, user)
			messages.info(request, f"You are now logged in as {username}")
			messages.info(request, f"An email has been sent to  {sEmail}")
			return redirect("main:homepage")
		else:
			for msg in form.error_messages:
				messages.error(request, f"{msg}: {form.error_messages[msg]}")
 

	form = NewUserForm
	return render(request,
				  "main/register.html",
				  context={"form":form})

def logout_request(request):
	logout(request)
	messages.info(request, "Logged out successfully!")
	return redirect("main:homepage")

def login_request(request):
	if request.method == "POST":
		form = AuthenticationForm(request, data=request.POST)
		if form.is_valid():
			username = form.cleaned_data.get('username')
			password = form.cleaned_data.get('password')
			user = authenticate(username=username, password=password)
			if user is not None:
				login(request, user)
				messages.info(request, f"You are now logged in as {username}")
				return redirect("main:homepage")
			else:
				messages.error(request, "Invalid username or password")

		else:
			messages.error(request, "Invalid username or password")

	form = AuthenticationForm()
	return render(request,
				  "main/login.html",
				  {"form":form})

main/templates/main/includes/messaging.html
 {% if messages %}
        {% for message in messages %}
            {% if message.tags == 'success'%}
                <script>M.toast({html: "{{message}}", classes: 'green rounded', displayLength:2000});</script>
            {% elif message.tags == 'info'%}
                <script>M.toast({html: "{{message}}", classes: 'blue rounded', displayLength:2000});</script>
            {% elif message.tags == 'warning'%}
                <script>M.toast({html: "{{message}}", classes: 'orange rounded', displayLength:10000});</script>
            {% elif message.tags == 'error'%}
                <script>M.toast({html: "{{message}}", classes: 'red rounded', displayLength:10000});</script>
            {% endif %}
        {% endfor %}
    {% endif %}

main/templates/main/includes/navbar.html
      
 

<li><a class="purple-text" href="/">Home</a></li>

{% if user.is_authenticated %}

<li><a class="purple-text" href="/">{{user.username|title}}</a></li>
<li><a class="purple-text" href="/logout">Logout</a></li>
<li><a class="active purple-text" href="/dashboard">Dashborad</a></li>
<li><a class="waves-effect waves-light btn-large " href="#getStarted" data-activates="dropdown1">GET STARTED</a></li>


<!-- sidenav login -->
<!-- <ul class="sidenav grey lighten-2" id="mobile-menu">
  <li><a href="/account">{{user.username|title}}</a></li>
  <li><a href="/logout">Logout</a></li>
  <li><a href="#service">Services</a></li>
  <li><a href="#contact">Contact</a></li> 
  <li><a class="waves-effect waves-light btn-large " href="#getStarted" data-activates="dropdown1">GET STARTED</a></li> -->
 
<!-- </ul> -->

{% else %}

<li><a class="purple-text modal-trigger" href="#register">Sign Up</a></li>
<li><a class="purple-text modal-trigger"  href="#login">Login</a></li>
<li><a class="purple-text" href="#service">Services</a></li>
<li><a class="purple-text" href="#contact">Contact</a></li>
<!-- <li><a class="waves-effect waves-light btn-large " href="#getStarted" data-activates="dropdown1">GET STARTED</a></li> -->




{% endif %}

<!-- sidenav not login -->
<!-- </ul> -->
<!-- <ul class="sidenav grey lighten-2" id="mobile-menu">
  <li><a class="purple-text" href="/register">Sign Up</a></li>
  <li><a class="purple-text" href="/login">Login</a></li>
  <li><a class="purple-text" href="#service">Services</a></li>
  <li><a class="purple-text" href="#contact">Contact</a></li>
  <li><a class="purple-text"  href="#!" data-activates="dropdown1">GET STARTED</a></li>

  
</ul>
 -->

main/templates/main/login.html
{% extends 'main/header.html' %}
{% load static %}


{% block content %}


    <div class="container" >
        <form method="POST" style="background-image: {% static 'login4.jpg' %}">
        {% csrf_token %}
        {{form.as_p}}
            <button style="background-color:#F4EB16; color:blue" class="btn btn-outline-info" type="submit">Login</button>
        </form>
        Don't have an account? <a href="/register" target="blank"><strong>register here</strong></a>!
    </div>




{% endblock %}





    

main/templates/main/market.html
{% load static %}

<link rel="stylesheet" href="{% static 'styles.css' %}">
    <link href="{% static 'tinymce/css/prism.css' %}" rel="stylesheet">
    <!-- Compiled and minified CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">

    <!--Import Google Icon Font-->
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  

<!-- FONT AWESOME WIDGETSS -->
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.4.1/css/all.css">
<style type="text/css">
	form{
      padding-top: 60px; 
      position: center;
      background-size: cover;
      background-position: center;
      min-height: 1000px;
      top: 100%
     /* opacity:0.85;*/
      
}
@media screen and (max-width: 670px){
  div{
        min-height: 500px;
      }

	
</style>


<div class="container" >
        <form method="POST" action="{% url 'main:create' %}" enctype="multipart/form-data">
        {% csrf_token %}
        {{form.as_p}}
            <input type="submit" value="Submit">

        </form>
        
</div>

   






    

main/templates/main/register.html
{% extends 'main/header.html' %}

{% block content %}
    <br>
    <form method="POST">
        {% csrf_token %}
        {{form.as_p}}
        <button style="background-color:#F4EB16; color:blue" class="btn btn-outline-info" type="submit">Sign Up</button>
    </form>

    If you already have an account <a href="/login" target="blank"><strong class="btn btn-outline-info">login</strong></a> instead.

  <!--   If you already have an account <a href="/login" target="blank"><button style="background-color:#F4EB16; color:blue; border-radius: 40%" class="btn btn-outline-info">login</button>instead
 -->
{% endblock %}